# Site settings
title: Clojure Personal Notebook
email: jjb.carreno@gmail.com
description: > 
  Some personal notes while learning Clojure language
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://jjbcarreno.github.io" # the base hostname & protocol for your site
twitter_username: jose_carreno
github_username:  jjbcarreno

# Build settings
markdown: kramdown
